# Site
repository: Git repository where your resume will be hosted, only required if you are hosting on GitHub (eg. sproogen/modern-resume-theme)
# favicon: Directory of your favicon (eg. images/favicon.ico)(optional)

# Content configuration version
version: 2

# Personal info
name: Shereen Elsayed
title: Software Development Engineer
email: s_elsayed@ucsb.edu
website: https://shereenelsayed.github.io/

phone: +1 (805) 453-0597
# phone_title: Phone (Phone title override)
# website_title: Web (Website title override)

# Dark Mode (true/false/never)
darkmode: never

# Social links
github_username:  shereenelsayed
linkedin_username: shereen-hussein
# twitter_username: jekyllrb
# github_username:  jekyll
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
# instagram_username: jekyll
# linkedin_username: jekyll
# xing_username: jekyll
# pinterest_username: jekyll
# youtube_username: jekyll
# orcid_username: 0000-0000-0000-0000
# googlescholar_username: D847cGsAAAAJ

# Additional icon links
# additional_links:
# - title: Link name
#   icon: Font Awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&s=brands&m=free)
#   url: Link url (eg. https://google.com)
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&s=brands&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me (Use this to override about section title)
about_profile_image: Directory of profile image (eg. images/profile.jpg)
about_content: | # this will include new lines to allow paragraphs
  Greetings, I'm Shereen, a seasoned software development engineer that welcomes challenges and architects solutions. I hold dual master's degrees, one in computer science from UCSB, and the other in computer engineering from Cairo University. Over the past four years, my professional journey has encompassed valuable experiences at UCSB and Siemens Digital Industries Software. Within these roles, I honed a diverse set of technical and interpersonal skills, contributing to my holistic expertise in the field.
  
  I am most skilled in: <mark>Problem Solving</mark>, <mark>Designing Solutions</mark>
# Write an awesome description about yourself here, this supports markdown, so you can add [links](http://foobar.com) and highlight things <mark>like this</mark>.

# You can even add paragraphs by using empty lines like this and add anything else [markdown](https://www.markdownguide.org/getting-started#what-is-markdown) supports such as
#   - Lists
#   - Tables
#   - <a href="google.com">Links</a>
#   - Images ![alt text](/images/landscape-trees.jpg "Trees")
  

content:
  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        border: weak 
        title: University of California, Santa Barbara
        caption: 2021 - 2024
        sub_title: M.Sc Computer Science
        # quote: >
        #   Established in 1636, Harvard is the oldest higher education institution in the United States, and is widely regarded in terms of its influence, reputation, and academic pedigree as a leading university in not just the US but also the world.
        description: | # this will include new lines to allow paragraphs
          <h6>Lab:</h6> (RaceLab)[https://sites.cs.ucsb.edu/~ckrintz/racelab.html] with Prof. Chandra Krintz and Prof. Rich Wolski
          
          <h6>Research Focus:</h6>
          My research focus area is <mark>distributed systems</mark> and <mark>IOT</mark>. I worked in several projects:
          - [CSPOT](https://github.com/MAYHEM-Lab/cspot): It is a runtime system that amalgamates "Serverless" computing (i.e. Functions as a Service – FaaS) and distributed computing principles targeting Internet of Things (IoT) applications.
          - Designed a system that enhances the power consumption of authentication and authorization for IOT devices by 60%
          - [Caplets](https://github.com/shereenElSayed/caplets_implementation): Implemented the [CAPLETs paper](https://ieeexplore.ieee.org/document/9709087) algorithm

          <h6>Publications:</h6>
          - [DEPOT](https://sites.cs.ucsb.edu/~ckrintz/papers/depot23.pdf)
          - Authenticate and authorize IOT devices with less power (Submitted)

          <h6>Technologies and Skills:</h6>
            <mark>Distributed Systems</mark> <mark>IOT</mark> <mark>AWS</mark> <mark>Python</mark> <mark>C++</mark> <mark>Linux</mark> <mark>Docker</mark> <mark>Kafka</mark> <mark>Pub-Sub</mark> <mark>MQTT</mark> <mark>Terraform</mark> <mark>FaaS</mark> <mark>Algorithms</mark> <mark>Database</mark> <mark>AWS-GreenGrass</mark> <mark>AWS-IOT</mark>
    # content:
      - layout: left
        border: weak
        title: Cairo University
        caption: 2015 - 2019
        sub_title: M.Sc Computer Engineering
        # quote: >
        #   Established in 1636, Harvard is the oldest higher education institution in the United States, and is widely regarded in terms of its influence, reputation, and academic pedigree as a leading university in not just the US but also the world.
        description: | # this will include new lines to allow paragraphs
          Advisors: Prof. (Elsayed Hemayed)[https://eg.linkedin.com/in/elsayed-hemayed-27813a7] and Prof. (Mona Farouk)[https://eg.linkedin.com/in/mona-farouk]
          
          My research focus area is <mark>NLP</mark> for Egyptian Arabic dialect using <mark>machine learning</mark> and <mark>neural networks</mark>. I created my own (dataset)[https://github.com/shery91/Egyptian-Dialect-Gender-Annotated-Dataset] and manually annotated 10K tweets 

          Publications:
          - [Gender identification of Egyptian dialect in twitter](https://www.sciencedirect.com/science/article/pii/S1110866518302044?via%3Dihub) - 21 citations
          - [Gender Identification for Egyptian Arabic Dialect in Twitter Using Deep Learning](https://www.sciencedirect.com/science/article/pii/S1110866520301158) - 12 citations 
        
          Technologies and Skills:
            <mark>Python</mark> <mark>NLP</mark> <mark>Machine Learning</mark> <mark>Neural Networks</mark>
    # content:
      - layout: left
        title: Cairo University
        caption: 2009 - 2014
        sub_title: B.Sc Computer Engineering
        description: |
          Graduation project: 3D Virtual meetings platform

  - title: Work Experience
    layout: list
    content:
      - layout: right
        title: Company name
        sub_title: Job title
        caption: Date Range (eg. November 2016 - present)
        link: Link to company (optional)
        quote: >
          Short description of the company (optional)
        description: | # this will include new lines to allow paragraphs
          Description of role

  - title: A Little More About Me
    layout: text
    content: | # this will include new lines to allow paragraphs
      This is where you can write a little more about yourself. You could title this section **Interests** and include some of your other interests.

      Or you could title it **Skills** and write a bit more about things that make you more desirable, like *leadership* or *teamwork*

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
# theme: modern-resume-theme (Use this is you are hosting your resume yourself)
# remote_theme: sproogen/modern-resume-theme (Use this if you are hosting your resume on GitHub)

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag

exclude : [
  "Gemfile",
  "Gemfile.lock",
  "node_modules",
  "vendor/bundle/",
  "vendor/cache/",
  "vendor/gems/",
  "vendor/ruby/",
  "lib/",
  "scripts/",
  "docker-compose.yml",
  ]
